name: CI/CD prodxcloud-multi-tenant-saas-sam-cli

on:
  push:
    branches: 
        - main
        - master
        - develop
        - 'release/*'
    tags: 
        - prod-v*
  pull_request:
    branches: 
        - main
        - master
        - develop
        - 'release/*'
env:
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: "ap-southeast-1"   



jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
            node-version: 18.x
      - name: Install dependencies
        run: npm install

      - name: Install esbuild
        run:  npm install -g esbuild
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env. AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # sam build 
      - run: sam build
      # Run Unit tests- Specify unit tests here 
      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-serverless-typescript ##s3-bucket## --capabilities CAPABILITY_IAM --region ##region## 
