on:
  push:
    branches:
      - main
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
            node-version: 18.x
      - name: Install dependencies
        run: npm install

      - name: Install esbuild
        run:  npm install -g esbuild
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # sam build 
      - run: sam build

      # Run Unit tests- Specify unit tests here 

      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name multi-tenant-saas-sam-serverless-typescript --s3-bucket ##s3-bucket## --capabilities CAPABILITY_IAM --region ##region## 
